name: Spring boot agendaProChallenge 

on:
  push:
    branches: [ "master" ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      working-directory: ./challenge/
      run: mvn -B test
  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build app
        working-directory: ./challenge/
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        working-directory: ./challenge/
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} docker.io
      - name: Build docker image
        working-directory: ./challenge/
        run: docker build -t juansotoa/challengeagendapro .
      - name: Publish image to docker hub
        working-directory: ./challenge/
        run: docker push juansotoa/challengeagendapro:latest
  deploy:
    needs: build
    name: Deploy to aws-ec2
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Pull Image from docker hub
        working-directory: ./challenge/
        run: sudo docker pull juansotoa/challengeagendapro:latest
      - name: Delete old container
        working-directory: ./challenge/
        run: sudo docker rm -f juansotoa-challengeagendapro-container
      - name: Run docker container
        working-directory: ./challenge/
        run: sudo docker run -d -p 8080:8080 --name juansotoa-challengeagendapro-container juansotoa/challengeagendapro
